Models/ErrorViewModel.cs
namespace Daynamic_Chart.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/SalesEntity.cs
using System.ComponentModel.DataAnnotations;

namespace Daynamic_Chart.Models
{
    public class SalesEntity
    {
        [Key]
        public int Id { get; set; }
        public string Monthname { get; set; }
        public int TotalSales { get; set; }
    }
}

Controllers/HomeController.cs
using Daynamic_Chart.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Daynamic_Chart.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SalesRecordsController.cs
using Microsoft.AspNetCore.Mvc;
using Daynamic_Chart.DataLayer;
using Daynamic_Chart.Models;

namespace Daynamic_Chart.Controllers
{
    public class SalesRecordsController : Controller
    {
        private readonly DbContextSales _context;
        public SalesRecordsController(DbContextSales context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ShowSalesData()
        {
            return View(); 
        }

        [HttpPost]
        public List<object> GetSalesData()
        {
            List<object> data = new List<object>();
            List<string> labels = _context.SalesData.Select(p=>p.Monthname).ToList();
            data.Add(labels);

            List<int> SalesNumber = _context.SalesData.Select(p => p.TotalSales).ToList();
            data.Add(SalesNumber);

            return data;
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/SalesRecords/ShowSalesData.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>
    <div class="row">
        <div class="col-1">
            <label><b>Chart-Type</b></label>
        </div>
        <div class="col-2">
            <select id="ChartType" class="form-control" style="width:150px;">
                <option selected>--Select Chart Type--</option>
                <option>bar</option>
                <option>line</option>
                <option>pie</option>
                <option>doughnut</option>
            </select>
        </div>
        <div class="col-4">
            <input id="ID" value="Show Graph" type="button" />
        </div>
    </div>
</p>


<br/>

<div id="ChartView">
    <canvas id="myChart"></canvas>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript">
    
    $(function(){
        $("#ID").click(function (){

            var chartType = $("#ChartType").val();
            var chartView = document.getElementById('ChartView');

            chartView.innerHTML = '&nbsp;'
            $('#ChartView').append('<canvas id = "myChart" style="max-width:750px; max-height:400px;"></canvas>' );


            $.ajax({
                type: "POST",
                url: "/SalesRecords/GetSalesData",
                data : "",
                contextType: "application/json; charset=utf-8",
                dataType : "json",
                success: OnSuccessResult,
                error : OnError
            });

            function OnSuccessResult (data){
                
                var _data = data;
                var _chartLabels = _data[0];
                var _chartData = _data[1];
            
                var barColor = ["red","green","blue","orange","brown","purple"];

                new Chart("myChart",{
                    type : chartType,
                    data :{
                        labels : _chartLabels,
                        datasets : [{
                            backgroundColor : barColor,
                            data : _chartData
                        }]
                    }
                });
            }


            function OnError(err) {

            }
        });
    });
    

</script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Daynamic_Chart</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Daynamic_Chart.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Daynamic_Chart</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SalesRecords" asp-action="ShowSalesData">Chart Data</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <script src="~/lib/jquery/dist/jquery.min.js"></script>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Daynamic_Chart - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>